"""
file_generator.py
-----------------
Turns a list of parsed resource dicts (from schema_parser) into a full
on-disk folder tree:

  <service>/
  ├── modules/
  │   └── <resource_name>/
  │       ├── variables.tf
  │       ├── main.tf
  │       └── outputs.tf
  ├── profiles/
  │   └── .gitkeep
  ├── test/
  │   └── .gitkeep
  ├── dr/
  │   └── .gitkeep
  ├── versions.tf
  └── README.md
"""

from __future__ import annotations

import os
import textwrap
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def generate_service_folder(
    base_dir: str | Path,
    provider_name: str,
    service_name: str,
    resources: list[dict[str, Any]],
    provider_meta: dict[str, str],
) -> Path:
    """
    Write the full service folder under *base_dir* and return its path.

    Parameters
    ----------
    base_dir       – directory where the service folder will be created
    provider_name  – e.g. "aws"
    service_name   – e.g. "s3"
    resources      – list of parsed resource dicts from schema_parser
    provider_meta  – {"namespace":…, "type":…, "version":…}
    """
    root = Path(base_dir) / service_name
    root.mkdir(parents=True, exist_ok=True)

    # Scaffold static directories
    for static_dir in ("profiles", "test", "dr"):
        d = root / static_dir
        d.mkdir(exist_ok=True)
        (d / ".gitkeep").touch()

    # modules/<resource>/
    modules_dir = root / "modules"
    modules_dir.mkdir(exist_ok=True)

    for res in resources:
        _write_module(modules_dir, res)

    # top-level versions.tf
    (root / "versions.tf").write_text(
        _render_versions_tf(provider_meta), encoding="utf-8"
    )

    # top-level README.md
    (root / "README.md").write_text(
        _render_readme(provider_name, service_name, resources, provider_meta),
        encoding="utf-8",
    )

    return root


# ---------------------------------------------------------------------------
# Module writer
# ---------------------------------------------------------------------------

def _write_module(modules_dir: Path, res: dict[str, Any]) -> None:
    mod_dir = modules_dir / res["name"]
    mod_dir.mkdir(parents=True, exist_ok=True)

    (mod_dir / "variables.tf").write_text(
        _render_variables(res), encoding="utf-8"
    )
    (mod_dir / "main.tf").write_text(
        _render_main(res), encoding="utf-8"
    )
    (mod_dir / "outputs.tf").write_text(
        _render_outputs(res), encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# variables.tf
# ---------------------------------------------------------------------------

def _render_variables(res: dict[str, Any]) -> str:
    lines: list[str] = [
        f"# variables.tf — {res['name']}",
        f"# Auto-generated by terraform-generator. Edit as needed.",
        "",
    ]

    attrs = res["attributes"]
    block_types = res["block_types"]

    # Required attributes first, then optional
    for required in (True, False):
        for attr_name, meta in attrs.items():
            if attr_name == "id":
                continue  # 'id' is always computed; skip as input
            if meta["required"] != required:
                continue
            if meta["computed"] and not meta["optional"] and not meta["required"]:
                continue  # purely computed → goes in outputs only

            lines.append(f'variable "{attr_name}" {{')

            hcl_type = meta["type"]
            lines.append(f'  type        = {hcl_type}')

            desc = meta["description"] or _humanise(attr_name)
            lines.append(f'  description = {_quote(desc)}')

            if meta["sensitive"]:
                lines.append(f'  sensitive   = true')

            if not meta["required"]:
                default = _default_for_type(hcl_type)
                lines.append(f'  default     = {default}')

            lines.append("}")
            lines.append("")

    # One variable per block_type (passed as an object/list)
    for block_name, bmeta in block_types.items():
        lines += _block_type_variable(block_name, bmeta)

    return "\n".join(lines)


def _block_type_variable(block_name: str, bmeta: dict[str, Any]) -> list[str]:
    """Generate a single variable block representing a nested block_type."""
    nesting   = bmeta["nesting_mode"]
    min_items = bmeta["min_items"]
    required  = min_items > 0

    # Build object shape from block attributes
    inner_attrs = bmeta["attributes"]
    if inner_attrs:
        obj_fields = ", ".join(
            f"{k} = {v['type']}" for k, v in inner_attrs.items()
        )
        obj_type = f"object({{{obj_fields}}})"
    else:
        obj_type = "any"

    if nesting in ("list", "set"):
        hcl_type = f"list({obj_type})"
        default  = "[]"
    elif nesting == "map":
        hcl_type = f"map({obj_type})"
        default  = "{}"
    else:  # single
        hcl_type = obj_type
        default  = "null"

    lines = [
        f'variable "{block_name}" {{',
        f'  type        = {hcl_type}',
        f'  description = {_quote(_humanise(block_name) + " block configuration")}',
    ]
    if not required:
        lines.append(f'  default     = {default}')
    lines.append("}")
    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# main.tf
# ---------------------------------------------------------------------------

def _render_main(res: dict[str, Any]) -> str:
    kind = res["kind"]
    name = res["name"]
    logical_name = "this"

    lines: list[str] = [
        f"# main.tf — {name}",
        f"# Auto-generated by terraform-generator. Edit as needed.",
        "",
    ]

    if kind == "resource":
        lines.append(f'resource "{name}" "{logical_name}" {{')
    else:
        # data source
        lines.append(f'data "{name}" "{logical_name}" {{')

    # ── Required attributes (always present) ────────────────────────────
    req_attrs = {
        k: v for k, v in res["attributes"].items()
        if k != "id" and v["required"]
    }
    if req_attrs:
        lines.append("  # --- required attributes ---")
    for attr_name, meta in req_attrs.items():
        lines.append(f'  {attr_name} = var.{attr_name}')

    # ── Optional attributes (null-guarded so they are omitted when unset) ─
    opt_attrs = {
        k: v for k, v in res["attributes"].items()
        if k != "id"
        and not v["required"]
        and not (v["computed"] and not v["optional"])
    }
    if opt_attrs:
        lines.append("")
        lines.append("  # --- optional attributes (omitted when null / default) ---")
    for attr_name, meta in opt_attrs.items():
        hcl_type = meta["type"]
        # Choose the right "empty / unset" sentinel per type
        if hcl_type.startswith("list(") or hcl_type.startswith("set("):
            guard = f'length(var.{attr_name}) > 0 ? var.{attr_name} : null'
        elif hcl_type == "bool":
            # bools have no meaningful null-guard; emit directly
            guard = f'var.{attr_name}'
        else:
            guard = f'var.{attr_name} != null ? var.{attr_name} : null'
        lines.append(f'  {attr_name} = {guard}')

    # ── Block types (dynamic for_each — fully flexible) ───────────────────
    for block_name, bmeta in res["block_types"].items():
        nesting   = bmeta["nesting_mode"]
        min_items = bmeta["min_items"]
        inner_attrs = list(bmeta["attributes"].keys())
        inner_blocks = list(bmeta["block_types"].keys())

        lines.append("")
        if nesting == "single":
            lines.append(f"  # --- optional nested block: {block_name} ---")
            lines.append(f"  dynamic \"{block_name}\" {{")
            lines.append(f"    for_each = var.{block_name} != null ? [var.{block_name}] : []")
            lines.append(f"    content {{")
            for a in inner_attrs:
                lines.append(f"      {a} = {block_name}.value.{a}")
            for b in inner_blocks:
                lines.append(f"      dynamic \"{b}\" {{")
                lines.append(f"        for_each = lookup({block_name}.value, \"{b}\", null) != null ? [{block_name}.value.{b}] : []")
                lines.append(f"        content {{}}")
                lines.append(f"      }}")
            lines.append(f"    }}")
            lines.append(f"  }}")
        else:
            qualifier = "required" if min_items > 0 else "optional"
            lines.append(f"  # --- {qualifier} repeatable block: {block_name} (for_each over list) ---")
            lines.append(f"  dynamic \"{block_name}\" {{")
            lines.append(f"    for_each = var.{block_name} != null ? var.{block_name} : []")
            lines.append(f"    content {{")
            for a in inner_attrs:
                lines.append(f"      {a} = {block_name}.value.{a}")
            for b in inner_blocks:
                lines.append(f"      dynamic \"{b}\" {{")
                lines.append(f"        for_each = lookup({block_name}.value, \"{b}\", null) != null ? [{block_name}.value.{b}] : []")
                lines.append(f"        content {{}}")
                lines.append(f"      }}")
            lines.append(f"    }}")
            lines.append(f"  }}")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# outputs.tf
# ---------------------------------------------------------------------------

def _render_outputs(res: dict[str, Any]) -> str:
    kind = res["kind"]
    name = res["name"]
    logical_name = "this"

    ref_prefix = f'resource."{name}".{logical_name}' if kind == "resource" \
                 else f'data."{name}".{logical_name}'

    # Use the proper HCL reference syntax
    if kind == "resource":
        ref_prefix = f'{name}.{logical_name}'
    else:
        ref_prefix = f'data.{name}.{logical_name}'

    lines: list[str] = [
        f"# outputs.tf — {name}",
        f"# Auto-generated by terraform-generator. Edit as needed.",
        "",
    ]

    # Always output 'id' if it exists
    if "id" in res["attributes"]:
        lines += [
            f'output "{name}_id" {{',
            f'  description = "The ID of the {name} resource."',
            f'  value       = {ref_prefix}.id',
            "}",
            "",
        ]

    # Output every computed attribute
    for attr_name, meta in res["attributes"].items():
        if attr_name == "id":
            continue
        if not meta["computed"]:
            continue
        desc = meta["description"] or _humanise(attr_name)
        out_block = [
            f'output "{name}_{attr_name}" {{',
            f'  description = {_quote(desc)}',
        ]
        if meta["sensitive"]:
            out_block.append('  sensitive   = true')
        out_block += [
            f'  value       = {ref_prefix}.{attr_name}',
            "}",
            "",
        ]
        lines += out_block

    if len(lines) == 3:
        lines.append("# No computed attributes found for this resource.")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# versions.tf (top-level)
# ---------------------------------------------------------------------------

def _render_versions_tf(provider_meta: dict[str, str]) -> str:
    namespace = provider_meta["namespace"]
    ptype     = provider_meta["type"]
    version   = provider_meta["version"]

    return textwrap.dedent(f"""\
        # versions.tf — pinned provider versions (auto-generated)
        terraform {{
          required_version = ">= 1.3.0"

          required_providers {{
            {ptype} = {{
              source  = "{namespace}/{ptype}"
              version = "~> {version}"
            }}
          }}
        }}
    """)


# ---------------------------------------------------------------------------
# README.md (top-level)
# ---------------------------------------------------------------------------

def _render_readme(
    provider_name: str,
    service_name: str,
    resources: list[dict[str, Any]],
    provider_meta: dict[str, str],
) -> str:
    version   = provider_meta["version"]
    namespace = provider_meta["namespace"]
    ptype     = provider_meta["type"]

    resource_list = "\n".join(
        f"| `{r['name']}` | {r['kind'].replace('_', ' ').title()} |"
        for r in resources
    )

    module_usage_blocks = []
    for r in resources:
        required_vars = [
            f'  {a} = "<value>"'
            for a, m in r["attributes"].items()
            if m["required"] and a != "id"
        ]
        required_str = "\n".join(required_vars) or "  # no required variables"
        block = textwrap.dedent(f"""\
            ### `{r['name']}`
            ```hcl
            module "{r['name']}" {{
              source = "./modules/{r['name']}"

            {required_str}
            }}
            ```
        """)
        module_usage_blocks.append(block)

    modules_section = "\n".join(module_usage_blocks) if module_usage_blocks \
                      else "_No resources matched this service prefix._"

    return textwrap.dedent(f"""\
        # {provider_name.upper()} — {service_name} Service Module

        > Auto-generated by **terraform-generator**
        > Provider: `{namespace}/{ptype}` · Version: `~> {version}`

        ## Overview

        This folder contains Terraform modules for every **{provider_name}_{service_name}_***
        resource and data-source exposed by the `{ptype}` provider.

        ## Folder Structure

        ```
        {service_name}/
        ├── modules/          # One sub-folder per resource / data-source
        ├── profiles/         # Combine modules here (scaffold)
        ├── test/             # Manual / automated test placeholder
        ├── dr/               # Disaster-recovery placeholder
        ├── versions.tf       # Pinned provider + Terraform versions
        └── README.md         # This file
        ```

        ## Resources Included

        | Resource / Data-Source | Kind |
        |------------------------|------|
        {resource_list}

        ## Usage

        {modules_section}

        ## Requirements

        | Name      | Version     |
        |-----------|-------------|
        | terraform | >= 1.3.0    |
        | {ptype:<9} | ~> {version} |

        ## Notes

        - All `variables.tf` files are generated directly from the provider schema.
        - Required variables have **no** default value — you must supply them.
        - Optional variables default to `null` / `[]` / `{{}}` as appropriate.
        - `outputs.tf` exposes every **computed** attribute of each resource.
        - The `profiles/`, `test/`, and `dr/` directories are empty scaffolds.

        ---
        *Generated with [terraform-generator](https://github.com/your-org/terraform-generator)*
    """)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _humanise(snake: str) -> str:
    """Convert snake_case to a readable sentence fragment."""
    return snake.replace("_", " ").capitalize()


def _quote(s: str) -> str:
    """Return a valid HCL string literal (double-quoted, escaped)."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    return f'"{escaped}"'


def _default_for_type(hcl_type: str) -> str:
    """Return a sensible HCL default literal for a given type string."""
    if hcl_type == "bool":
        return "false"
    if hcl_type == "number":
        return "null"
    if hcl_type.startswith("list(") or hcl_type.startswith("set("):
        return "[]"
    if hcl_type.startswith("map("):
        return "{}"
    # object(...) / string / any / unknown → null is always safe
    return "null"
